---
# to configure apache 
- name: httpd conf file 
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
  notify: 
      restart apache service 

- name: copy first page
  copy: src=index.html dest=/var/www/html/index.html

